# Generated by Django 2.2.16 on 2022-09-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220918_0218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscribe',
        ),
    ]
