# Generated by Django 2.2.16 on 2022-09-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220918_0258'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscribe',
        ),
    ]
